# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset

In [2]:
df = pd.read_csv("/kaggle/input/datasets/zain280/titanic-data-set/train.csv")
df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.00,0,0,SOTON/OQ 392076,7.0500,NaN,S
146,147,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.00,0,0,350043,7.7958,NaN,S
801,802,1,2,"Collyer, Mrs. Harvey (Charlotte Annie Tate)",female,31.00,1,1,C.A. 31921,26.2500,NaN,S
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.00,0,0,111240,33.5000,B19,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.00,1,5,347082,31.2750,NaN,S
400,401,1,3,"Niskanen, Mr. Juha",male,39.00,0,0,STON/O 2. 3101289,7.9250,NaN,S
773,774,0,3,"Elias, Mr. Dibo",male,NaN,0,0,2674,7.2250,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
738,739,0,3,"Ivanoff, Mr. Kanio",male,NaN,0,0,349201,7.8958,NaN,S
571,572,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.00,2,0,11769,51.4792,C101,S

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Train_Test_Split

In [6]:
#starter columns
df.drop(['PassengerId','Name','Ticket'],axis =1,inplace = True)
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [7]:
#train columns
X = df.drop(['Survived'],axis = 1)
X

     Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         3    male  22.0      1      0   7.2500   NaN        S
1         1  female  38.0      1      0  71.2833   C85        C
2         3  female  26.0      0      0   7.9250   NaN        S
3         1  female  35.0      1      0  53.1000  C123        S
4         3    male  35.0      0      0   8.0500   NaN        S
..      ...     ...   ...    ...    ...      ...   ...      ...
886       2    male  27.0      0      0  13.0000   NaN        S
887       1  female  19.0      0      0  30.0000   B42        S
888       3  female   NaN      1      2  23.4500   NaN        S
889       1    male  26.0      0      0  30.0000  C148        C
890       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 8 columns]

In [8]:
#traget column
y  = df['Survived']
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [9]:
#train_test_split_code

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state = 42)

In [10]:
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare    Cabin Embarked
331       1    male  45.5      0      0   28.5000     C124        S
733       2    male  23.0      0      0   13.0000      NaN        S
382       3    male  32.0      0      0    7.9250      NaN        S
704       3    male  26.0      1      0    7.8542      NaN        S
813       3  female   6.0      4      2   31.2750      NaN        S
..      ...     ...   ...    ...    ...       ...      ...      ...
106       3  female  21.0      0      0    7.6500      NaN        S
270       1    male   NaN      0      0   31.0000      NaN        S
860       3    male  41.0      2      0   14.1083      NaN        S
435       1  female  14.0      1      2  120.0000  B96 B98        S
102       1    male  21.0      0      1   77.2875      D26        S

[712 rows x 8 columns]

In [11]:
X_test

     Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
709       3    male   NaN      1      1  15.2458   NaN        C
439       2    male  31.0      0      0  10.5000   NaN        S
840       3    male  20.0      0      0   7.9250   NaN        S
720       2  female   6.0      0      1  33.0000   NaN        S
39        3  female  14.0      1      0  11.2417   NaN        C
..      ...     ...   ...    ...    ...      ...   ...      ...
433       3    male  17.0      0      0   7.1250   NaN        S
773       3    male   NaN      0      0   7.2250   NaN        C
25        3  female  38.0      1      5  31.3875   NaN        S
84        2  female  17.0      0      0  10.5000   NaN        S
10        3  female   4.0      1      1  16.7000    G6        S

[179 rows x 8 columns]

In [12]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [13]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: Survived, Length: 179, dtype: int64

In [14]:
X_train.isnull().sum()

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Cabin       553
Embarked      2
dtype: int64

In [15]:
X_test.isnull().sum()

Pclass        0
Sex           0
Age          37
SibSp         0
Parch         0
Fare          0
Cabin       134
Embarked      0
dtype: int64

# Missing Values Handling

In [16]:
# Numerical missing value imputation - Age column (Mean)

from sklearn.impute import SimpleImputer

age_imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')

age_imputer.fit(X_train[['Age']])

X_train['Age'] = age_imputer.transform(X_train[['Age']])
X_test['Age'] = age_imputer.transform(X_test[['Age']])

In [17]:
X_train.isnull().sum()

Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Cabin       553
Embarked      2
dtype: int64

In [18]:
X_test.isnull().sum()

Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Cabin       134
Embarked      0
dtype: int64

In [19]:
# Categorical missing value imputation - Embarked column (Most Frequent)

embarked_imputer = SimpleImputer(missing_values = np.nan,strategy = 'most_frequent')

embarked_imputer.fit(X_train[['Age']])

X_train['Embarked'] = embarked_imputer.transform(X_train[['Age']]).ravel()

In [20]:
X_train.isnull().sum()

Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Cabin       553
Embarked      0
dtype: int64

In [21]:

# Categorical missing value imputation with indicator - Cabin column
X_train['Cabin_indicator'] = X_train['Cabin'].isna()
X_test['Cabin_indicator'] = X_test['Cabin'].isna()

# Imputation
imputer = SimpleImputer(strategy='constant', fill_value='Missing')

X_train['Cabin'] = imputer.fit_transform(X_train[['Cabin']]).ravel()
X_test['Cabin'] = imputer.transform(X_test[['Cabin']]).ravel()

In [22]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_indicator
331,1,male,45.500000,0,0,28.5000,C124,45.500000,False
733,2,male,23.000000,0,0,13.0000,Missing,23.000000,True
382,3,male,32.000000,0,0,7.9250,Missing,32.000000,True
704,3,male,26.000000,1,0,7.8542,Missing,26.000000,True
813,3,female,6.000000,4,2,31.2750,Missing,6.000000,True
...,...,...,...,...,...,...,...,...,...
106,3,female,21.000000,0,0,7.6500,Missing,21.000000,True
270,1,male,29.498846,0,0,31.0000,Missing,29.498846,True
860,3,male,41.000000,2,0,14.1083,Missing,41.000000,True
435,1,female,14.000000,1,2,120.0000,B96 B98,14.000000,False
102,1,male,21.000000,0,1,77.2875,D26,21.000000,False

In [23]:
X_train.isnull().sum()

Pclass             0
Sex                0
Age                0
SibSp              0
Parch              0
Fare               0
Cabin              0
Embarked           0
Cabin_indicator    0
dtype: int64

In [24]:
X_test.isnull().sum()

Pclass             0
Sex                0
Age                0
SibSp              0
Parch              0
Fare               0
Cabin              0
Embarked           0
Cabin_indicator    0
dtype: int64

# Outlier Detection

In [25]:
# using z-Score 

#age column

mean_of_age = X_train['Age'].mean()
std_of_age = X_train["Age"].std()
X_train['zscore_Age'] = (X_train['Age']-mean_of_age)/std_of_age
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_indicator,zscore_Age
331,1,male,45.500000,0,0,28.5000,C124,45.500000,False,1.231398e+00
733,2,male,23.000000,0,0,13.0000,Missing,23.000000,True,-5.001304e-01
382,3,male,32.000000,0,0,7.9250,Missing,32.000000,True,1.924808e-01
704,3,male,26.000000,1,0,7.8542,Missing,26.000000,True,-2.692600e-01
813,3,female,6.000000,4,2,31.2750,Missing,6.000000,True,-1.808396e+00
...,...,...,...,...,...,...,...,...,...,...
106,3,female,21.000000,0,0,7.6500,Missing,21.000000,True,-6.540440e-01
270,1,male,29.498846,0,0,31.0000,Missing,29.498846,True,2.734055e-16
860,3,male,41.000000,2,0,14.1083,Missing,41.000000,True,8.850920e-01
435,1,female,14.000000,1,2,120.0000,B96 B98,14.000000,False,-1.192742e+00
102,1,male,21.000000,0,1,77.2875,D26,21.000000,False,-6.540440e-01

In [26]:
outliers_age = X_train[abs(X_train['zscore_Age']) >3]

print(len(outliers_age))

display(outliers_age)

5

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_indicator,zscore_Age
116,3,male,70.5,0,0,7.750,Missing,70.5,True,3.155317
745,1,male,70.0,1,1,71.000,B22,70.0,False,3.116839
630,1,male,80.0,0,0,30.000,A23,80.0,False,3.886407
851,3,male,74.0,0,0,7.775,Missing,74.0,True,3.424666
672,2,male,70.0,0,0,10.500,Missing,70.0,True,3.116839

In [27]:
#fare
mean_of_fare = X_train['Fare'].mean()
std_of_fare = X_train['Fare'].std()

X_train['zscore_Fare'] = (X_train["Fare"]-mean_of_fare)/std_of_fare
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_indicator,zscore_Age,zscore_Fare
331,1,male,45.500000,0,0,28.5000,C124,45.500000,False,1.231398e+00,-0.078628
733,2,male,23.000000,0,0,13.0000,Missing,23.000000,True,-5.001304e-01,-0.376880
382,3,male,32.000000,0,0,7.9250,Missing,32.000000,True,1.924808e-01,-0.474533
704,3,male,26.000000,1,0,7.8542,Missing,26.000000,True,-2.692600e-01,-0.475896
813,3,female,6.000000,4,2,31.2750,Missing,6.000000,True,-1.808396e+00,-0.025232
...,...,...,...,...,...,...,...,...,...,...,...
106,3,female,21.000000,0,0,7.6500,Missing,21.000000,True,-6.540440e-01,-0.479825
270,1,male,29.498846,0,0,31.0000,Missing,29.498846,True,2.734055e-16,-0.030523
860,3,male,41.000000,2,0,14.1083,Missing,41.000000,True,8.850920e-01,-0.355554
435,1,female,14.000000,1,2,120.0000,B96 B98,14.000000,False,-1.192742e+00,1.682019
102,1,male,21.000000,0,1,77.2875,D26,21.000000,False,-6.540440e-01,0.860143

In [28]:
outliers_fare = X_train[abs(X_train["zscore_Fare"])>3]
print(len(outliers_fare))
display(outliers_fare)

17

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_indicator,zscore_Age,zscore_Fare
118,1,male,24.000000,0,1,247.5208,B58 B60,24.000000,False,-4.231736e-01,4.135780
716,1,female,38.000000,0,0,227.5250,C45,38.000000,False,6.542216e-01,3.751020
377,1,male,27.000000,0,2,211.5000,C82,27.000000,False,-1.923032e-01,3.442666
742,1,female,21.000000,2,2,262.3750,B57 B59 B63 B66,21.000000,False,-6.540440e-01,4.421605
380,1,female,42.000000,0,0,227.5250,Missing,42.000000,True,9.620488e-01,3.751020
779,1,female,43.000000,0,1,211.3375,B3,43.000000,False,1.039006e+00,3.439539
730,1,female,29.000000,0,0,211.3375,B5,29.000000,False,-3.838960e-02,3.439539
88,1,female,23.000000,3,2,263.0000,C23 C25 C27,23.000000,False,-5.001304e-01,4.433631
341,1,female,24.000000,3,2,263.0000,C23 C25 C27,24.000000,False,-4.231736e-01,4.433631
557,1,male,29.498846,0,0,227.5250,Missing,29.498846,True,2.734055e-16,3.751020
737,1,male,35.000000,0,0,512.3292,B101,35.000000,False,4.233512e-01,9.231235
679,1,male,36.000000,0,1,512.3292,B51 B53 B55,36.000000,False,5.003080e-01,9.231235
438,1,male,64.000000,1,4,263.0000,C23 C25 C27,64.000000,False,2.655098e+00,4.433631
689,1,female,15.000000,0,1,211.3375,B5,15.000000,False,-1.115785e+00,3.439539
258,1,female,35.000000,0,0,512.3292,Missing,35.000000,True,4.233512e-01,9.231235
27,1,male,19.000000,3,2,263.0000,C23 C25 C27,19.000000,False,-8.079576e-01,4.433631
700,1,female,18.000000,1,0,227.5250,C62 C64,18.000000,False,-8.849144e-01,3.751020

In [29]:
# IQR

#age

age_Q1 = X_train["Age"].quantile(0.25)
age_Q3 = X_train['Age'].quantile(0.75)

age_IQR = age_Q3 - age_Q1

age_minimum = age_Q1-(1.5*age_IQR)
age_maximum = age_Q3-(1.5*age_IQR)
print(age_minimum,age_maximum)

2.5 15.5

In [30]:
age_outlier_IQR = X_train[(X_train["Age"]<age_minimum)|(X_train['Age']>age_maximum)]
print(len(age_outlier_IQR))
display(age_outlier_IQR)

666

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_indicator,zscore_Age,zscore_Fare
331,1,male,45.500000,0,0,28.5000,C124,45.500000,False,1.231398e+00,-0.078628
733,2,male,23.000000,0,0,13.0000,Missing,23.000000,True,-5.001304e-01,-0.376880
382,3,male,32.000000,0,0,7.9250,Missing,32.000000,True,1.924808e-01,-0.474533
704,3,male,26.000000,1,0,7.8542,Missing,26.000000,True,-2.692600e-01,-0.475896
118,1,male,24.000000,0,1,247.5208,B58 B60,24.000000,False,-4.231736e-01,4.135780
...,...,...,...,...,...,...,...,...,...,...,...
71,3,female,16.000000,5,2,46.9000,Missing,16.000000,True,-1.038828e+00,0.275425
106,3,female,21.000000,0,0,7.6500,Missing,21.000000,True,-6.540440e-01,-0.479825
270,1,male,29.498846,0,0,31.0000,Missing,29.498846,True,2.734055e-16,-0.030523
860,3,male,41.000000,2,0,14.1083,Missing,41.000000,True,8.850920e-01,-0.355554
102,1,male,21.000000,0,1,77.2875,D26,21.000000,False,-6.540440e-01,0.860143

In [31]:
fare_Q1 = X_train["Fare"].quantile(0.25)
fare_Q3 = X_train["Fare"].quantile(0.75)

fare_IQR = fare_Q3-fare_Q1

fare_minimum = max(0,fare_Q1 - 1.5 * fare_IQR)
fare_maximum = fare_Q3 + 1.5 * fare_IQR

print(fare_minimum , fare_maximum)

0 64.3625

In [32]:
fare_outlier_IQR = X_train[(X_train['Fare']<fare_minimum) | (X_train['Fare']>fare_maximum)]

print(len(fare_outlier_IQR))
display(fare_outlier_IQR)

96

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_indicator,zscore_Age,zscore_Fare
118,1,male,24.0,0,1,247.5208,B58 B60,24.0,False,-0.423174,4.135780
486,1,female,35.0,1,0,90.0000,C93,35.0,False,0.423351,1.104757
716,1,female,38.0,0,0,227.5250,C45,38.0,False,0.654222,3.751020
390,1,male,36.0,1,2,120.0000,B96 B98,36.0,False,0.500308,1.682019
377,1,male,27.0,0,2,211.5000,C82,27.0,False,-0.192303,3.442666
...,...,...,...,...,...,...,...,...,...,...,...
681,1,male,27.0,0,0,76.7292,D49,27.0,False,-0.192303,0.849400
385,2,male,18.0,0,0,73.5000,Missing,18.0,True,-0.884914,0.787264
700,1,female,18.0,1,0,227.5250,C62 C64,18.0,False,-0.884914,3.751020
435,1,female,14.0,1,2,120.0000,B96 B98,14.0,False,-1.192742,1.682019
102,1,male,21.0,0,1,77.2875,D26,21.0,False,-0.654044,0.860143

In [33]:
# z score outlier detection is better for age outliers

# Keeping only the training rows where the absolute Z-score (|Z|) is less than or equal to 3.
X_train = X_train[abs(X_train['zscore_Age']) <=3]

X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_indicator,zscore_Age,zscore_Fare
331,1,male,45.500000,0,0,28.5000,C124,45.500000,False,1.231398e+00,-0.078628
733,2,male,23.000000,0,0,13.0000,Missing,23.000000,True,-5.001304e-01,-0.376880
382,3,male,32.000000,0,0,7.9250,Missing,32.000000,True,1.924808e-01,-0.474533
704,3,male,26.000000,1,0,7.8542,Missing,26.000000,True,-2.692600e-01,-0.475896
813,3,female,6.000000,4,2,31.2750,Missing,6.000000,True,-1.808396e+00,-0.025232
...,...,...,...,...,...,...,...,...,...,...,...
106,3,female,21.000000,0,0,7.6500,Missing,21.000000,True,-6.540440e-01,-0.479825
270,1,male,29.498846,0,0,31.0000,Missing,29.498846,True,2.734055e-16,-0.030523
860,3,male,41.000000,2,0,14.1083,Missing,41.000000,True,8.850920e-01,-0.355554
435,1,female,14.000000,1,2,120.0000,B96 B98,14.000000,False,-1.192742e+00,1.682019
102,1,male,21.000000,0,1,77.2875,D26,21.000000,False,-6.540440e-01,0.860143

In [34]:
minimum_zscore_fare = X_train[abs(X_train['zscore_Fare']) <=3]['Fare'].max()

print((minimum_zscore_fare))

164.8667

In [35]:
X_train['Fare']= X_train['Fare'].clip(fare_minimum , fare_maximum)

X_train['Fare'].max()

/tmp/ipykernel_16/1394324696.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Fare']= X_train['Fare'].clip(fare_minimum , fare_maximum)

64.3625

In [36]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_indicator,zscore_Age,zscore_Fare
331,1,male,45.500000,0,0,28.5000,C124,45.500000,False,1.231398e+00,-0.078628
733,2,male,23.000000,0,0,13.0000,Missing,23.000000,True,-5.001304e-01,-0.376880
382,3,male,32.000000,0,0,7.9250,Missing,32.000000,True,1.924808e-01,-0.474533
704,3,male,26.000000,1,0,7.8542,Missing,26.000000,True,-2.692600e-01,-0.475896
813,3,female,6.000000,4,2,31.2750,Missing,6.000000,True,-1.808396e+00,-0.025232
...,...,...,...,...,...,...,...,...,...,...,...
106,3,female,21.000000,0,0,7.6500,Missing,21.000000,True,-6.540440e-01,-0.479825
270,1,male,29.498846,0,0,31.0000,Missing,29.498846,True,2.734055e-16,-0.030523
860,3,male,41.000000,2,0,14.1083,Missing,41.000000,True,8.850920e-01,-0.355554
435,1,female,14.000000,1,2,64.3625,B96 B98,14.000000,False,-1.192742e+00,1.682019
102,1,male,21.000000,0,1,64.3625,D26,21.000000,False,-6.540440e-01,0.860143

In [37]:
X_train.drop(['zscore_Age','zscore_Fare'],axis=1 , inplace=True)

X_train

/tmp/ipykernel_16/1674476712.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train.drop(['zscore_Age','zscore_Fare'],axis=1 , inplace=True)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_indicator
331,1,male,45.500000,0,0,28.5000,C124,45.500000,False
733,2,male,23.000000,0,0,13.0000,Missing,23.000000,True
382,3,male,32.000000,0,0,7.9250,Missing,32.000000,True
704,3,male,26.000000,1,0,7.8542,Missing,26.000000,True
813,3,female,6.000000,4,2,31.2750,Missing,6.000000,True
...,...,...,...,...,...,...,...,...,...
106,3,female,21.000000,0,0,7.6500,Missing,21.000000,True
270,1,male,29.498846,0,0,31.0000,Missing,29.498846,True
860,3,male,41.000000,2,0,14.1083,Missing,41.000000,True
435,1,female,14.000000,1,2,64.3625,B96 B98,14.000000,False
102,1,male,21.000000,0,1,64.3625,D26,21.000000,False